import "@repo/ui/styles.css";
import "../globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GetSession from "@/components/GetSession";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GetSession>

      <body className={GeistSans.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
      </GetSession>
    </html>
  );
}
